### ISSUE TITLE
DM contact options missing on 

### ISSUE THREAD

**Issue by wowpatrick** [scy/me#1]
There are no ways to personally contact @scy mentioned in the README.md, e.g. e-mail or other means apart form Twitter DM.

**Comment by scy** [comment]
You're right, thanks @wowpatrick! I have to think a bit about possible spam implications, but in the mean time you can use e-mail to contact `scy` at the domain `scy.name` or `mail` at another domain called `timweber.name`. 😉

**Comment by wowpatrick** [comment]
👍 Thanks for the quick response! Maybe a link to `scy.name` on the `README.md` would be helpful for someone who want's to get in contact by you. But I also totally get if you don't want to directly linkt to that page.

**Comment by scy** [comment]
Oh well, there's a reason why I don't want to link to scy.name, yeah … it's old, it's ugly and I'm partially even ashamed of it. I have plans for a new website, but … ⌚️ 😩

**Comment by scy** [comment]
In the mean time, there's now https://timweber.name/ with some contact options.

**Comment by scy** [comment]
Has been addressed in <https://codeberg.org/scy/me/commit/5bb89ec3d174cef234b7443330f7fde1f3be957c>.
